Repository gnome-terminator/terminator, pull requests merged in 2020-04, with the labels that each got.

#6 Implement support for Python 3
  po/POTFILES.in
  remotinator
  setup.py
  terminator
  terminatorlib/__init__.py
  terminatorlib/borg.py
  terminatorlib/config.py
  terminatorlib/configobj/__init__.py
  terminatorlib/configobj/configobj.py
  terminatorlib/configobj/validate.py
  terminatorlib/container.py
  terminatorlib/cwd.py
  terminatorlib/debugserver.py
  terminatorlib/editablelabel.py
  terminatorlib/encoding.py
  terminatorlib/factory.py
  terminatorlib/freebsd.py
  terminatorlib/ipc.py
  terminatorlib/keybindings.py
  terminatorlib/layoutlauncher.py
  terminatorlib/notebook.py
  terminatorlib/optionparse.py
  terminatorlib/paned.py
  terminatorlib/plugin.py
  terminatorlib/plugins/activitywatch.py
  terminatorlib/plugins/custom_commands.py
  terminatorlib/plugins/logger.py
  terminatorlib/plugins/maven.py
  terminatorlib/plugins/terminalshot.py
  terminatorlib/plugins/testplugin.py
  terminatorlib/plugins/url_handlers.py
  terminatorlib/prefseditor.py
  terminatorlib/pylint.sh
  terminatorlib/searchbar.py
  terminatorlib/signalman.py
  terminatorlib/terminal.py
  terminatorlib/terminal_popup_menu.py
  terminatorlib/terminator.py
  terminatorlib/titlebar.py
  terminatorlib/translation.py
  terminatorlib/util.py
  terminatorlib/version.py
  terminatorlib/window.py
  tests/test_doctests.py
  tests/testborg.py
  tests/testsignalman.py
Labels: enhancement

#9 Converting to python 3 and making all tests pass.
  .gitignore
  tests/testsignalman.py
Labels: bug

#15 update the INSTALL file
  INSTALL
  setup.py
Labels: quality

#17 Add GitHub action for Python
  .github/workflows/python.yml
Labels: quality

#18 Fix some compat issues for Python 2.7
  .github/workflows/python.yml
  terminatorlib/terminal.py
  terminatorlib/util.py
Labels: bug

#22 terminal: Add compat detection for Vte regexp feature
  terminatorlib/terminal.py
Labels: bug

#7 Removing packaging files from the repository
  debian/README.source
  debian/changelog
  debian/compat
  debian/control
  debian/copyright
  debian/docs
  debian/rules
  debian/source/format
  debian/terminator.links
  debian/terminator.postinst
  debian/terminator.preinst
  debian/terminator.prerm
  debian/watch
  terminator.spec
Labels: enhancement

#28 terminal: Improve compat for Vte Regex
  terminatorlib/terminal.py
Labels: bug, quality

#27 Remove obsolete terminator.wrapper
  MANIFEST.in
  setup.py
  terminator.wrapper
Labels: quality

#30 Update pt_BR.po
  po/pt_BR.po
Labels: i18n

#19 Only import GdkX11 when available
  terminatorlib/keybindings.py
  terminatorlib/terminator.py
  terminatorlib/window.py
Labels: enhancement

#43 searchbar: Implement modern/glib regexp support
  terminatorlib/regex.py
  terminatorlib/searchbar.py
  terminatorlib/terminal.py
Labels: bug

#33 Add FreeBSD
  INSTALL
Labels: documentation
