Repository gnome-terminator/terminator, pull requests merged in 2020-06, with the labels that each got.

#88 Do not crash when dbus server is unavailable, just emit an error message
  terminatorlib/ipc.py
Labels: bug

#110 add debug logging to searchbar
  terminatorlib/searchbar.py
Labels: quality

#46 Added option to disable ctrl+mousewheel zoom
  terminatorlib/config.py
  terminatorlib/preferences.glade
  terminatorlib/prefseditor.py
  terminatorlib/terminal.py
Labels: enhancement

#113 Fix crash when GdkX11 module is not available when creating layout
  terminatorlib/terminator.py
Labels: bug

#112 fix traceback when closing a window
  terminatorlib/terminal.py
Labels: quality

#109 fix io errors on debugserver
  terminatorlib/debugserver.py
Labels: quality
