Repository gnome-terminator/terminator, pull requests merged in 2020-05, with the labels that each got.

#51 Disable special logic for pasting on Wayland
  terminatorlib/terminal.py
Labels: bug

#54 fix traceback on dragging and dropping files from a file manager
  terminatorlib/terminal.py
Labels: bug

#53 Install AppStream data as .metainfo.xml
  setup.py
Labels: enhancement

#52 fix up language strings in .po files
  po/ckb.po
  po/en_AU.po
  po/en_CA.po
  po/en_GB.po
  po/es.po
  po/fy.po
  po/nl.po
  po/oc.po
  po/ru_RU.po
  po/si.po
  po/tyv.po
  po/zh_CN.po
  po/zh_TW.po
Labels: i18n, quality

#50 Switch to setuptools and use pytest
  .github/workflows/python.yml
  .gitignore
  MANIFEST.in
  pytest.ini
  run_tests
  setup.cfg
  setup.py
  terminatorlib/borg.py
  terminatorlib/debugserver.py
  terminatorlib/freebsd.py
  terminatorlib/plugin.py
  terminatorlib/pylint.sh
  tests/test_borg.py
  tests/test_doctests.py
  tests/test_signalman.py
Labels: quality

#66 docs: Update INSTALL.md and add distributions
  INSTALL
  INSTALL.md
Labels: documentation

#67 Update AUTHORS with a full list from GIT history
  .authors.footer
  .authors.header
  .mailmap
  AUTHORS
  RELEASE.md
Labels: documentation

#77 update the INSTALL.md for Ubuntu installation
  INSTALL.md
Labels: documentation

#86 Gentoo: github is only a mirror
  INSTALL.md
Labels: documentation

#42 Add layout launcher to terminal popup menu.
  terminatorlib/terminal_popup_menu.py
Labels: enhancement

#91 Import Launchpad translations
  po/hr.po
  po/pl.po
  po/pt.po
  po/pt_BR.po
Labels: i18n

#70 replace gettext and intltool with Babel
  .gitignore
  DEVELOPMENT.md
  babel.cfg
  data/terminator.desktop
  data/terminator.metainfo.xml
  po/genpot.sh
  po/terminator.pot
  po/update_all_po.sh
  setup.cfg
  setup.py
Labels: enhancement, i18n

#100 Revert "replace gettext and intltool with Babel"
  .gitignore
  DEVELOPMENT.md
  babel.cfg
  data/terminator.appdata.xml.in
  data/terminator.desktop.in
  po/genpot.sh
  po/terminator.pot
  po/update_all_po.sh
  setup.cfg
  setup.py
Labels: quality

#61 Propagate tab-swictch events if there is only one tab
  terminatorlib/terminal.py
Labels: enhancement
