Repository gnome-terminator/terminator, pull requests merged in 2022-10, with the labels that each got.

#653 - bug context menu (right click)->layouts->"Layout Name" always selec…
  terminatorlib/terminal_popup_menu.py
Labels: bug, reproduction

#651 Fix typos
  CHANGELOG.legacy.txt
  CHANGELOG.md
  data/layout-files-examples/README.md
  terminatorlib/container.py
  terminatorlib/editablelabel.py
  terminatorlib/notebook.py
  terminatorlib/plugins/logger.py
  terminatorlib/plugins/run_cmd_on_match.py
  terminatorlib/preferences.glade
  terminatorlib/prefseditor.py
  terminatorlib/searchbar.py
  terminatorlib/terminal.py
  terminatorlib/terminator.py
  terminatorlib/util.py
  terminatorlib/window.py
Labels: quality

#628 Fix missing icons when started with Ctrl-Alt-T
  terminator
Labels: bug

#632 this line has an extra ';' symbol
  terminatorlib/util.py
Labels: quality
