Repository gnome-terminator/terminator, pull requests merged in 2023-04, with the labels that each got.

#735 Remove more unused settings and update the docs accordingly
  doc/terminator.1
  doc/terminator.adoc
  terminatorlib/config.py
  terminatorlib/prefseditor.py
Labels: quality

#747 Rewrite terminator_config.5 man page in AsciiDoc format
  doc/gen_manpages.sh
  doc/terminator_config.5
  doc/terminator_config.adoc
Labels: documentation

#698 Add detachable tabs feature to preferences
  terminatorlib/config.py
  terminatorlib/notebook.py
  terminatorlib/preferences.glade
  terminatorlib/prefseditor.py
Labels: enhancement
